Update menu

diff --git a/herramientas/menu b/herramientas/menu
--- a/herramientas/menu
+++ b/herramientas/menu
@@ -4,8 +4,8 @@ gren=$(tput setaf 2)
 yellow=$(tput setaf 3)
 #Screen
 [[ ! -e /usr/bin/trans ]] && { 
-echo -e "Piratear es muy feo, toma verg�enza en la cara"
-echo -e "Di duro para llegar hasta aqu�, Muchas noches sin dormir"
+echo -e "Piratear es muy feo, toma vergüenza en la cara"
+echo -e "Di duro para llegar hasta aquí, Muchas noches sin dormir"
 echo -e "Adquiere un Serial y Ayuda al desarrollador"
 }
 SCPdir="/etc/newadm" && [[ ! -d ${SCPdir} ]] && exit 1
@@ -56,7 +56,7 @@ SEMCOR='\e[0m'
   -azu)cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
   -verd)cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
   -bra)cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
-  "-bar2"|"-bar")cor="\e[1;30m➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\e[0m" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
+  "-bar2"|"-bar")cor="\e[1;30mâž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–\e[0m" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
   -azuc)cor="${COLOR[7]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
   -rojoc)cor="${COLOR[8]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
 esac
@@ -108,7 +108,7 @@ atualiza_fun () {
 cd $HOME
 tput cuu1 && tput dl1
 msg -bar2
-msg -ama "$(fun_trans "ACTUALIZADOR ADM SCRIPTS"): \033[1;32m[ NEW - ULTIMATE - SCRIPT ]  \033[1;33m[\033[1;34m OFICIAL BY DANKELTHAHER \033[1;33m] \033[1;31m[\033[1;37mFINAL\033[1;31m]"
+msg -ama "$(fun_trans "ACTUALIZADOR ADM SCRIPTS"): \033[1;32m[ NEW - @THEVIX12 ]  \033[1;33m[\033[1;34m *THE-VIX-PERÚ* @THEVIX12 \033[1;33m] \033[1;31m[\033[1;37mFINAL\033[1;31m]"
 msg -verm "$(fun_trans "Al proseguir los datos como el tiempo de uso seran perdidos"): "
 msg -bar2
 while [[ $Key != @(s|S|y|Y|n|N) ]]; do
@@ -332,7 +332,7 @@ fi
 IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 sleep 1s
 [[ -e ${SCPfrm}/lista-arq ]] && {
-  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY DE INSTALA�AO!" ]]; then
+  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY DE INSTALAï¿½AO!" ]]; then
   echo -e "\033[1;33m$(fun_trans "KEY DE INSTALACION NO DEBE SER USADA AQUI")"
   msg -bar2
   rm ${SCPfrm}/lista-arq
@@ -445,11 +445,11 @@ eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Et
     msg -bar
     read -p " [S/N]: " -e -i n sshsn
            [[ "$sshsn" = @(s|S|y|Y) ]] && {
-           echo -e "${cor[1]} $(fun_trans "Correcci�n de problemas de paquetes en SSH ...")"
-           echo -e " $(fun_trans "�Cual es la tasa RX?")"
+           echo -e "${cor[1]} $(fun_trans "Correcciï¿½n de problemas de paquetes en SSH ...")"
+           echo -e " $(fun_trans "ï¿½Cual es la tasa RX?")"
            echo -ne "[ 1 - 999999999 ]: "; read rx
            [[ "$rx" = "" ]] && rx="999999999"
-           echo -e " $(fun_trans "�Cual es la tarifa TX")"
+           echo -e " $(fun_trans "ï¿½Cual es la tarifa TX")"
            echo -ne "[ 1 - 999999999 ]: "; read tx
            [[ "$tx" = "" ]] && tx="999999999"
            apt-get install ethtool -y > /dev/null 2>&1
@@ -557,7 +557,7 @@ case $1 in
 "ssl.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -azu "SSL Dropbear $(pid_inst stunnel4)";;
 "ssld.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -azu "SSL Manager $(pid_inst stunnel4)";;
 "sslmanager.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -ama "SSL MANAGERS $(pid_inst stunnel4)";;
-"errormanager.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -ama "Corrección De Puertos $(pid_inst errormanager)";;
+"errormanager.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -ama "CorrecciÃ³n De Puertos $(pid_inst errormanager)";;
 "shadown.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -bra "Shadowsocks Cloack $(pid_inst ck-server)";;
 "shadowsock.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -bra "Shadowsocks-R,Go,Liv $(pid_inst obfs-serv)";;
 "shadowsocks.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -bra "Shadowsocks-Libev $(pid_inst obfs-serv)";;
@@ -613,7 +613,7 @@ selection=$(selection_fun $Numb)
   esac
   }  
 }
-# Menu Instala��o
+# Menu Instalaï¿½ï¿½o
 pid_inst () {
 [[ $1 = "" ]] && echo -e "\033[1;31m[off]" && return 0
 unset portas
@@ -626,7 +626,7 @@ var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | 
     let i++
     }
 done <<< "$portas_var"
-[[ $(echo "${portas[@]}"|grep "$1") ]] && echo -e "\033[1;32m[on]" || echo -e "\033[1;31m[off]"
+[[ $(echo "${portas[@]}"|grep "$1") ]] && echo -e "\033[1;32m[ACTIVO]" || echo -e "\033[1;31m[DESACTIVADO]"
 }
 menu_inst () {
 export -f fun_eth
@@ -681,9 +681,9 @@ tput cuu1 >&2 && tput dl1 >&2
 done
 echo $selection
 }
-on="\033[1;32m[ON]" && off="\033[1;31m[OFF]"
+on="\033[1;32m[ACTIVADO]" && off="\033[1;31m[DESACTIVADO]"
 [[ $(ps x | grep badvpn | grep -v grep | awk '{print $1}') ]] && badvpn=$on || badvpn=$off
-# EXECU��O MENU
+# EXECUï¿½ï¿½O MENU
 export -f msg
 export -f selection_fun
 export -f fun_trans
@@ -708,9 +708,9 @@ msg -ne "$(fun_trans "DIRECCION DE LA MAQUINA"): " && msg -bra "$(meu_ip)"
 [[ -e ${SCPdir}/key.txt ]] && msg -bar && msg -bra "USER-KEY: $(cat ${SCPdir}/key.txt)"
 # NOVO SISTEMA DE MENUS
 msg -bar
-msg -ama "$(fun_trans "MANAGER") \033[1;31m[\033[1;32m ALAN TECK\033[1;31m] \033[1;33m[\033[1;34m ELLA NO TE AMA \033[1;33m] \033[1;31m[\033[1;37mFINAL\033[1;31m] "
+msg -ama "$(fun_trans "MANAGER") \033[1;31m[\033[1;32m *THE-VIX-PERÚ* \033[1;31m] \033[1;33m[\033[1;34m@THEVIX12  \033[1;33m] \033[1;31m[\033[1;37mLO MEJOR\033[1;31m] "
 msg -bar
-menu_func "ADMINISTRAR USUARIOS" "HERRAMIENTAS Y EXTRAS" "MENU DE INSTALACIONES" "-vd ACTUALIZACION" "-vm DESINSTALAR" "-fi $AutoRun INICIO AUTOMATICO" "CAMBIAR IDIOMA" "CAMBIAR COLORES" "-azc WEB PANEL (sshplus)"
+menu_func "ADMINISTRAR USUARIOS" "HERRAMIENTAS Y EXTRAS" "MENU DE INSTALACIONES" "-vd ACTUALIZACION" "-vm DESINSTALAR" "-fi $AutoRun INICIO AUTOMATICO" "PUERTOS ACTIVOS" "CAMBIAR COLORES" "-azc WEB PANEL (sshplus)"
 echo -ne "$(msg -verd "[0]") $(msg -verm2 ">") " && msg -bra "$(fun_trans "SALIR DEL SCRIPT")"
 msg -bar
 # FIM
@@ -722,7 +722,7 @@ case ${selection} in
 4)atualiza_fun;;
 5)remove_script;;
 6)fun_autorun;;
-7)funcao_idioma;;
+7)mine_port;;
 8)canbio_color;;
 9)${SCPfrm}/panelweb.sh "${idioma}";;
 0)cd $HOME && exit 0;;
